### ISSUE TITLE
on Mac mlflow can not connect to DB

### ISSUE THREAD

**Issue by PhilipMay** [PhilipMay/mlflow4docker#11]

**Comment by michalharakal** [comment]
I can reproduce the issue also on the Apple Silicon Mac (ARM).

**Comment by michalharakal** [comment]
I am getting the following error:
```(Background on this error at: https://sqlalche.me/e/14/e3q8)
mlflow4docker-mlflow-1     | Operation will be retried in 51.1 seconds
mlflow4docker-mlflow-1     | 2021/12/02 13:44:17 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
mlflow4docker-mlflow-1     | (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```
which can be explained with this https://stackoverflow.com/questions/69573312/python-psycopg2-scram-authentication

**Comment by PhilipMay** [comment]
We might solve that issue by not using the binary package. But building it could be difficult. See here:

https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary

**Comment by PhilipMay** [comment]
@michalharakal here is the fix: https://github.com/PhilipMay/mlflow4docker/commit/0e2dca7e2a0882f9470776e975fae5a6a29926f0

Can you pull from git and check again please?

**Comment by michalharakal** [comment]
Fix has helped. Now its working. Thank you @PhilipMay

**Comment by PhilipMay** [comment]
Ok. Thanks for feedback @michalharakal 
Closing this.
